# Generated by Django 3.0.6 on 2021-02-24 21:42

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
          model_name='post',
          name='created_date',
          field=models.DateTimeField(default=timezone.now, editable=True),
        ),
        migrations.AlterField(
          model_name='comment',
          name='created_date',
          field=models.DateTimeField(default=timezone.now, editable=True),
        ),
        migrations.AddField(
          model_name='comment',
          name='post_title',
          field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
