# Generated by Django 3.0.6 on 2021-02-25 12:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210224_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_title',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]