# Generated by Django 2.2.5 on 2019-12-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191227_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
