# Generated by Django 3.0.6 on 2021-02-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='satellite',
            table=None,
        ),
    ]
