# Generated by Django 3.0.6 on 2021-01-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210121_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('rover_url', models.CharField(blank=True, max_length=200, null=True)),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('landing_date', models.DateTimeField(auto_now_add=True)),
                ('max_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cameras', models.ManyToManyField(to='frontend.Camera')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
