# Generated by Django 3.0.6 on 2021-01-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_camera_rover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='landing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rover',
            name='launch_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rover',
            name='max_date',
            field=models.DateTimeField(),
        ),
    ]
