# Generated by Django 3.0.6 on 2021-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210126_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
