# Generated by Django 3.0.6 on 2021-01-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rover_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rover',
            name='cameras',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Rover',
        ),
    ]
