"""
Django settings for mySpaceStuff project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pathlib import Path
import django_heroku
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')


my_file = Path(".env")
if my_file.exists():
  from decouple import config
  SECRET_KEY = config('DJANGO_SECRET_KEY')
else:
  SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

IS_HEROKU_APP = "DYNO" in os.environ and not "CI" in os.environ

# SECURITY WARNING: don't run with debug turned on in production!
if not IS_HEROKU_APP:
  DEBUG = True
DEBUG = False

if IS_HEROKU_APP:
  ALLOWED_HOSTS = ["astrollaneous.herokuapp.com"]
else:
  ALLOWED_HOSTS = ['localhost', '127.0.0.1']

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'whitenoise.runserver_nostatic',
  'django.contrib.staticfiles',
  'widget_tweaks',
  'rest_framework',
  'knox',
  'accounts.apps.AccountsConfig',
  'frontend.apps.FrontendConfig',
  'blog.apps.BlogConfig',
]

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
}

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'whitenoise.middleware.WhiteNoiseMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'corsheaders.middleware.CorsMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ('http://localhost:8000', 'https://localhost:8000', 'http://astrollaneous.herokuapp.com', 'https://astrollaneous.herokuapp.com')

ROOT_URLCONF = 'mySpaceStuff.urls'

TEMPLATES = [
  {
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [os.path.join(BASE_DIR, 'build'), TEMPLATE_DIR],
  'APP_DIRS': True,
  'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'mySpaceStuff.wsgi.application'

# DATABASES = {
#   # 'default': {
#   #   'ENGINE': 'django.db.backends.sqlite3',
#   #   'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#   # }
#   "default": {
#     "ENGINE": "django.db.backends.postgresql",
#     "NAME": "ddhuvdnv1ln37",
#     "USER": "dvhwfkepdfwomk",
#     "PASSWORD": "cfc2d62a8866ee2882aa2ceed053098bf7d46c777353f625abb2773b05a40187",
#     "HOST": "ec2-52-5-167-89.compute-1.amazonaws.com",
#     "PORT": "5432",
#   }
# }

if IS_HEROKU_APP:
  # In production on Heroku the database configuration is derived from the `DATABASE_URL`
  # environment variable by the dj-database-url package. `DATABASE_URL` will be set
  # automatically by Heroku when a database addon is attached to your Heroku app. See:
  # https://devcenter.heroku.com/articles/provisioning-heroku-postgres
  # https://github.com/jazzband/dj-database-url
  DATABASES = {
    "default": dj_database_url.config(
      conn_max_age=600,
      conn_health_checks=True,
      ssl_require=True,
    ),
  }
else:
  # When running locally in development or in CI, a sqlite database file will be used instead
  # to simplify initial setup. Longer term it's recommended to use Postgres locally too.
  DATABASES = {
    "default": {
      "ENGINE": "django.db.backends.sqlite3",
      "NAME": os.path.join(BASE_DIR, 'db.sqlite3'),
    }
  }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

CACHES = {
  'default': {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
  }
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


INTERNAL_IPS = ['127.0.0.1']

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# TBD: additional EMAIL configuration needed for email server


LOGGING = {
  'version': 1,
  'disable_existing_loggers': False,
  'handlers': {
    'console': {
      'class': 'logging.StreamHandler',
    },
  },
  'root': {
      'handlers': ['console'],
      'level': 'DEBUG',
  },
}


STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'build', 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [] 
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configure app for Heroku deployment
django_heroku.settings(locals())

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
